In [38]:
import torch
import numpy as np

In [39]:
x = np.random.randn(10, 10)

In [40]:
print("x.max(1) \n\n", x.max(1))

x.max(1) 

 [1.60996119 1.60620378 1.25905378 0.49584592 2.4911015  1.90920785
 1.38104195 1.94188    1.32262062 2.65719912]


In [41]:
print("torch.from_numpy(x).max(1)    \n\n", torch.from_numpy(x).max(1))

torch.from_numpy(x).max(1)    

 torch.return_types.max(
values=tensor([1.6100, 1.6062, 1.2591, 0.4958, 2.4911, 1.9092, 1.3810, 1.9419, 1.3226,
        2.6572], dtype=torch.float64),
indices=tensor([7, 0, 5, 1, 2, 4, 6, 7, 9, 6]))


In [42]:
# pytorchについて : max()[0] => 最大値を返す
print("torch.from_numpy(x).max(1)[0] \n\n", torch.from_numpy(x).max(1)[0])

torch.from_numpy(x).max(1)[0] 

 tensor([1.6100, 1.6062, 1.2591, 0.4958, 2.4911, 1.9092, 1.3810, 1.9419, 1.3226,
        2.6572], dtype=torch.float64)


In [43]:
# pytorchについて : max()[1] => 最大値に対応したindexを返す(argmax)
print("torch.from_numpy(x).max(1)[1] \n\n", torch.from_numpy(x).max(1)[1])


torch.from_numpy(x).max(1)[1] 

 tensor([7, 0, 5, 1, 2, 4, 6, 7, 9, 6])


In [52]:
source = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

# dim=1の方向に、indexを探して、出力する
# dim=1のときは、dim=1以外の次数が、sourceとindexであっていればOK
index  = torch.tensor([[0,0],[1,1],[2,2],[0,1]])
print(source.gather(dim=1, index=index))

print("\n-------------------------\n")

# dim=1の方向に、indexを探して、出力する
# dim=1のときは、dim=1以外の次数が、sourceとindexであっていればOK
index  = torch.tensor([[0],[1],[2],[0]])
source.gather(dim=1, index=index)

print("\n-------------------------\n")

tensor([[ 1,  1],
        [ 5,  5],
        [ 9,  9],
        [10, 11]])

-------------------------


-------------------------



In [53]:
source = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

# dim=0の方向に、indexを探して、出力する
# dim=0のときは、dim=0以外の次数が、sourceとindexであっていればOK
index  = torch.tensor([[0,0,0],[1,1,1],[2,2,2],[2,2,2]])
print(source.gather(dim=0, index=index))

print("\n-------------------------\n")

# dim=0の方向に、indexを探して、出力する
# dim=0のときは、dim=0以外の次数が、sourceとindexであっていればOK
index  = torch.tensor([[0,1,2]])
source.gather(dim=0, index=index)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9]])

-------------------------



tensor([[1, 5, 9]])